language: objective-c
xcode_project: CustomKeyboard.xcodeproj
xcode_scheme: CustomKeyboard

# osx_image: xcode7
# script:
# #- xctool -project ScrollImage.xcodeproj -scheme ScrollImage build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
# #– xctool -workspace TravisExample.xcworkspace -scheme TravisExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# - xctool -project ScrollImage.xcodeproj -scheme ScrollImage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

osx_image: xcode8
script:
#- xcodebuild -project {project}.xcodeproj -target {target} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#- xcodebuild -workspace {workspace}.xcworkspace -scheme {scheme} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild -project CustomKeyboard.xcodeproj -target CustomKeyboard -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO



#- xcodebuild -version && node --version && pwd && ls
